dist: xenial  # required for Python >= 3.7

language: python

python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# Not supported by Django < 1.11.17
  - "3.7"
  - "3.7-dev" # 3.7 development branch

cache: pip

env:
  - DJANGO_VERSION=1.11 # Unsupported after April 2020
# Not supported by some dependencies
# - DJANGO_VERSION=2.1
# - DJANGO_VERSION=2.2

install:
  - pip install django~=$DJANGO_VERSION  # Accept any version in series
  - pip install -r requirements.txt

script:
  - "python manage.py test"
  - "python manage.py migrate && python manage.py loaddata fixtures/demo.json"
  - "python -m pylint lowfat"